compiler-explorer/gcc-cross-builder

- build/1.24.0/powerpc64-at12.config
- build/1.24.0/powerpc64-at13.config
- build/1.24.0/powerpc64le-at12.config
- build/1.24.0/powerpc64le-at13.config
Its been a while since AT12.0 was added and since then gcc has moved to git. Update the package to build from the latest 12.0 release.
Also add AT13.0 based on gcc9.
Both of these use crosstool-ng-1.24 and are both for powerpc64 (big endian) and powerpc64le (little endian).
12.0 hash is from 
https://github.com/advancetoolchain/advance-toolchain/blob/master/configs/12.0/packages/gcc/sources#L26
13.0 hash is from
https://github.com/advancetoolchain/advance-toolchain/blob/master/configs/13.0/packages/gcc/sources#L26
Updates to compiler-explorer repository for AT13.0 still to come.
> update powerpc64 Advance toolchain 12 and add 13

- Dockerfile
`rsync` is required for installing kernel headers.
Let's make it available inside the container.
With this patch both GCC `10.2.0` RISC-V toolchains (`riscv64` and `riscv32`) can be
successfully built inside the docker container, specified by the `Dockerfile`.
Fixes https://github.com/compiler-explorer/compiler-explorer/issues/965 
Related to https://github.com/compiler-explorer/gcc-cross-builder/pull/5
> Dockerfile: add rsync to list of installed packages

- build/latest/arm-10.2.0.config
- build/latest/arm-9.3.0.config
- build/latest/arm-trunk.config
- build/latest/arm64-10.2.0.config
- build/latest/arm64-9.3.0.config
- build/latest/arm64-trunk.config
Hi All,
This adds new configurations for 
* Arm64 GCC 9.3.0
* Arm64 GCC 10.2.0
* Arm64 GCC (master/nightlies)
and
* Arm GCC 9.3.0
* Arm GCC 10.2.0
* Arm GCC (master/nightlies)
The toolchains are configured to mirror Arm's A-profile releases [1]
and each toolchain is created with the components at the same version
as these Arm releases.
For the AArch32 (Arm) releases this means they are configured by default
for -march=armv7-a -mfpu=neon -mfloat-abi=hard
[1] https://developer.arm.com/tools-and-software/open-source-software/developer-tools/gnu-toolchain/gnu-a/downloads
> Add support for GCC 9, 10 and master for AArch32 and AArch64 (A-profile)

- Dockerfile
- build/latest/arm-10.3.0.config
- build/latest/arm64-10.3.0.config
Hi All,
This adds new configurations for 
* Arm64 GCC 10.3.0
and
* Arm GCC 10.3.0
The toolchains are configured to mirror Arm's A-profile releases [1]
and each toolchain is created with the components at the same version
as these Arm releases.
For the AArch32 (Arm) releases this means they are configured by default
for -march=armv7-a -mfpu=neon -mfloat-abi=hard
Note that this also upgrades crosstools-ng to a version that supports
GCC 10.3.0. I have not updated the format of the existing config files
since I don't know how this is typically handled.
For reference I have done so with
cp latest/arm64-10.3.0.config .config
/opt/crosstool-ng-latest/bin/ct-ng upgradeconfig
/opt/crosstool-ng-latest/bin/ct-ng oldconfig
cp .config latest/arm64-10.3.0.config
[1] …
> Add GCC 10.3.0 for Arm64 and Arm

- Dockerfile
- build/latest/mips-11.2.0.config
- build/latest/mips64-11.2.0.config
- build/latest/powerpc-11.2.0.config
- build/latest/powerpc64-11.2.0.config
- build/latest/powerpc64le-11.2.0.config
- build/latest/s390-11.2.0.config
Update "latest" ct-ng to current dev version.
Use our own gcc 11.2.0 as the base compiler (needed to build cross GNAT
compiler).
Add cross gcc(c/c++/Ada) 11.2.0 for s390x-linux, mips-linux ppc, ppc64, ppc64le
and mips64-linux.
refs https://github.com/compiler-explorer/compiler-explorer/issues/3282
refs https://github.com/compiler-explorer/compiler-explorer/issues/2470
> Update ct-ng latest version, add new compilers, use GCC 11.2.0 as base

- Dockerfile
Hi All,
binutils seems to have added a dependency on zlib for building and so the nightly builds
have been failing.
This adds the zlib-dev package to the docker image so we can build the arm and arm64
nightlies again.
Thanks,
Tamar
> [compiler-explorer] Add zlib-dev as new dependency of binutils

- Dockerfile
- build/build.sh
Hi All,
#15 added the use of GCC 11.2 to compile toolchains with without setting the
loader path to use that GCC's libstdc++.  As a result the produced
cross compiler may use features from a libstdc++ that it doesn't know how to
find at runtime.
The arm nighties are failing[0] because of this as the stage-1 compiler is
unable to find the right GLIBCXX:
```
./xgcc: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by ./xgcc)
```
Normally you fix this by setting `LD_LIBRARY_PATH`, however crosstools-ng
immediately errors out here as it explicitly checks that you don't set
`LD_LIBRARY_PATH`.
It's however unclear to me why 11.2 is required, given that the GCC pre-reqs say
that GCC 5.1 is the minimum[1].  The only thing that is really required is a gnat …
> compiler-explorer: fix incorrect GCC 11 usage.

- Dockerfile
- build/latest/riscv32-10.3.0.config
- build/latest/riscv32-11.2.0.config
- build/latest/riscv32-8.5.0.config
- build/latest/riscv32-9.4.0.config
- build/latest/riscv64-10.3.0.config
- build/latest/riscv64-11.2.0.config
- build/latest/riscv64-8.5.0.config
- build/latest/riscv64-9.4.0.config
The current RISC-V (RV32 and RV64) support is a bit outdated, therefore I've updated it to support the following GCCs:
* 11.2.0
* 10.3.0
* 9.4.0
* 8.5.0
The crosstools-ng configs work fine on my local machine (Fedora), but the build fails in the Docker image of this repo with the following error message during pass-1 core C GCC compiler:
```
./xgcc: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by ./xgcc)
```
This means, that the Ubuntu 18.04 image contains a libstdc++ that is too old.
I did not dig any deeper (i.e. I can't say what is causing this issue), instead I focused on a solution.
To avoid regressions, I've therefore added a commit that solves this issue by pulling in a third-party PPA, which provides a more recent libstdc++:
``` …
```
> Update RISC-V support (and libstdc++)

- Dockerfile
Our dockerimage is using different versions of crosstool-ng.
Old version don't handle bash >= 4, so we can't simply bump
the version without breaking things.
The GCC 11 issue has been fixed differently in the meantime,
so the bump is not even needed now.
fixes #24
> Revert previous bump in ubuntu version

- Dockerfile
Update to latest version to have GCC 12.1 support.
> Bump crosstool-ng latest version

- build/latest/riscv32-12.1.0.config
- build/latest/riscv64-12.1.0.config
This patch adds GCC 12.1.0 configs for rv32 and rv64.
New compiler versions:
* riscv32-unknown-elf-gcc (crosstool-NG 1.25.0.24_a1365c3) 12.1.0
* riscv64-unknown-linux-gnu-gcc (crosstool-NG 1.25.0.24_a1365c3) 12.1.0
Note, that as of now ct-ng does not have GCC 12 support.
Therefore, this patch depends on a PR that can be found here:
https://github.com/crosstool-ng/crosstool-ng/pull/1739
> RISC-V: Add GCC 12.1.0

- build/latest/riscv32-11.3.0.config
- build/latest/riscv64-11.3.0.config
This patch adds GCC 11.3.0 configs for rv32 and rv64.
New compiler versions:
* riscv32-unknown-elf-gcc (crosstool-NG 1.25.0.23_5937024) 11.3.0
* riscv64-unknown-linux-gnu-gcc (crosstool-NG 1.25.0.23_5937024) 11.3.0
> RISC-V: Add GCC 11.3.0

- build/latest/powerpc64-11.2.0.config
The config was not correctly enabling GNAT/Ada.
https://github.com/compiler-explorer/compiler-explorer/issues/3701
> Fix GNAT from GCC 11.2.0 for PPC64

- build/latest/sh4-12.2.0.config
- build/latest/sh4-4.9.4.config
- build/latest/sh4-9.5.0.config
Add 3 configs for sh targets:
- old 4.9.4 unknown-elf (c/c++)
- 9.5 linux (c/c++/fortran/d/objc)
- 12.2.0 linux (c/c++/fortran/d/objc)
Old compiler were specificaly requested for Dreamcast hacking.
refs https://github.com/compiler-explorer/compiler-explorer/issues/94
> Add sh4 config

- build/latest/loongarch64-12.2.0.config
LoongArch is a new RISC ISA, which is a bit like MIPS or RISC-V, and today Linux/GCC/LLVM etc. support LoongArch. This patch is used to add LoongArch crosstools .config file.
Some useful links:
Crosstools-NG: "https://github.com/crosstool-ng/crosstool-ng/pull/1722"
Docs can be found: "https://loongson.github.io/LoongArch-Documentation/"
Signed-off-by: Qi Hu <huqi@loongson.cn>
> Add loongarch64 gcc 12.2.0

- Dockerfile
> Bump crosstool-ng version

- Dockerfile
Installs autoconf 2.71 from Jammy and bump ct-ng version again.
> Really bump crosstool-ng version

- build/latest/sparc-12.2.0.config
- build/latest/sparc-leon-12.2.0.config
- build/latest/sparc64-12.2.0.config
Add 3 new targets: sparc, sparc-leon and sparc64.
C, C++, Ada, D, Fortran, Objective-C and Go for sparc/sparc64
C, C++, D, Objective-C and Fortran for sparc-leon.
refs https://github.com/compiler-explorer/compiler-explorer/issues/266
> Add SPARC configs

- check_and_update_conf.py
As mentioned several times in reviews, the script emits useless .name properties for compilers where 'groupname semver' is applicable (which should be the case for most (every?) compilers).
> fix: finally make it skip .name in generated config

- build/latest/bpf-trunk.config
Add GCC for C and C++, for BPF target.
Only trunk build as BPF is still under heavy dev and existing GCC releases
don't make sense (yet).
refs compiler-explorer/compiler-explorer#4408
> add: gcc bpf cross compiler

- build/latest/bpf-trunk.config
ct-ng config has the "default to PIE" set, which is not correct for BPF.
fixes https://github.com/compiler-explorer/compiler-explorer/issues/4517
> fix: bpf: unset defaulting to PIE

- build/build-vax-netbsd.sh
Use NetBSD to build a cross compiler for VAX.
Can only build current GCC version used by NetBSD (10.4.0 now). Not possible to use it to build arbitrary GCC version. This may be done differently in a following change.
refs https://github.com/compiler-explorer/compiler-explorer/issues/4783
> Build script for vax-netbsd

- build/build-vax-netbsd.sh
The bespoke GHA wants a version number and this will probably be needed later when we add bare compiler.
refs https://github.com/compiler-explorer/compiler-explorer/issues/4783
> Tune vax-netbsd build script

- build/latest/msp430-12.1.0.config
The file was incorrectly using 12.2.
refs https://github.com/compiler-explorer/compiler-explorer/issues/5004
> Really use gcc 12.1.0 for the msp430 12.1.0 config

- Dockerfile
- build/latest/arm-13.1.0.config
- build/latest/arm64-13.1.0.config
- build/latest/avr-13.1.0.config
- build/latest/c6x-13.1.0.config
- build/latest/loongarch64-13.1.0.config
- build/latest/m68k-13.1.0.config
- build/latest/mips-13.1.0.config
- build/latest/mips64-13.1.0.config
- build/latest/mips64el-13.1.0.config
- build/latest/mipsel-13.1.0.config
- build/latest/msp430-13.1.0.config
- build/latest/powerpc-13.1.0.config
- build/latest/powerpc64-13.1.0.config
- build/latest/powerpc64le-13.1.0.config
- build/latest/riscv32-13.1.0.config
- build/latest/riscv64-13.1.0.config
- build/latest/s390x-13.1.0.config
- build/latest/sh-13.1.0.config
- build/latest/sparc-13.1.0.config
- build/latest/sparc-leon-13.1.0.config
- build/latest/sparc64-13.1.0.config
Enable as many languages as possible, can't really list them here, will
be more explicit in the config updates.
Bump the native base GCC used for building the cross compiler mainly for
building Ada as it's the most picky one (the rule being: use matching
version N to build cross-gcc N). GCC 12 is bumped to freshly built GCC
13.
Also introduce new cross for m68k.
refs https://github.com/compiler-explorer/compiler-explorer/issues/4987
refs https://github.com/compiler-explorer/compiler-explorer/issues/4904
> GCC 13.1 update for several targets

- build/build-vax-netbsd.sh
The script can be used to build arbitrary version based on old/new
GCC (in the context of NetBSD) and an optional timestamp.
Refs https://github.com/compiler-explorer/compiler-explorer/issues/5708
Co-authored-by: Jan-Benedict Glaw <jbglaw@lug-owl.de>
> vax: Update build script
